# src: ~/.config/vale/.vale.ini
### @(#)  : vale default config
#
# @version	1.0.0
# @date		2035-04-22
# @author	atsushifx  <atsushifx@aglabo.com>
# @license	MIT
#
# @description<<
# user default editorconfig :
# symlink this to ~ : user root
#<<

### Global Settings

MinAlertLevel = suggestion
Packages = proselint, Google, write-good, Hugo

# vocabularies
# Vocab =

###  Style settings by Ext
##
[*]
BasedOnStyles = Vale, Google, 18F, write-good,myStyle
