## @(#):  dirmngr setting
#
# @version  1.0.0
# @author   Furukawa Atsushi <atsushifx@gmail.com>
# @since    2025-02-20
# @license  MIT
#
# @desc<<
# This file configures Dirmngr for retrieving public keys
# from a reliable keyserver.
#<<

# Keyserver settings
keyserver hkps://keys.openpgp.org
