#!/usr/bin/env bash
##
# @(#) user specific bashrc
#
# @version  1.0.2
# @date     2024-04-10
# @author   Furukawa, Atsushi <atsushifx@aglabo.com>
# @license  MIT
#
# @desc <<
# user specific bashrc
# user defined bashrc
#<<

# local env settings

BASHRC_DIR="${XDG_CONFIG_HOME}/bash"
BASHSCRIPTS_DIR="${BASHRC_DIR}/scripts"

echo "Exec: .config/bash/bashrc"

### prompt : set prompt for bash
_set_prompt() {
  local _colorprompt

  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    _color_prompt=yes
  else
    _color_prompt=
  fi

  if [ "$_color_prompt" = yes ]; then
    PS1='[\[\033[01;32m\]\u@\h\[\033[34m\] \W\[\033[00m\]] \$ '
  else
    PS1='[ ${debian_chroot:+($debian_chroot)}\u@\h \w] \$ '
  fi
  export PS1
}
_set_prompt

### Alias
if [[ -f "${XDG_CONFIG_HOME}/aliases" ]]; then
  . "${XDG_CONFIG_HOME}/aliases"
fi

### key config

### bash completion

#   carapace completion
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense'
# source <(carapace _carapace)

###   compltion for local bashrc
# compleion scripts
_cmpl_d="${BASHRC_DIR}/completion.d"
if [[ -e "${_cmpl_d}" ]]; then
  for f in ${_cmpl_d}/*.{sh,bash}; do
    . "${f}"
  done
fi

# carapace
# export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
# source <(carapace _carapace)

# zoxide setup
# eval "$(zoxide init bash --hook prompt )"

### setup GnuPG
# export GNUPGHOME="${XDG_DATA_HOME}"/gnupg
# export GPG_TTY=$( tty )
GPGDIR=$(wslpath 'C:/app/develop/utils/GnuPG')
GPG_AGENT="${GPGDIR}/bin/gpg-connect-agent.exe"

# ソケット転送
# socat UNIX-LISTEN:$GNUPGHOME/S.gpg-agent,fork EXEC:"${GPG_AGENT} /bye",nofork

### wakatime-count
_watatime_script="${BASHSCRIPTS_DIR}/bash_wakatime.sh"
if [[ -f "${_watatime_script}" ]]; then
  source "${_watatime_script}"
fi


### from WSL goto ~/temp
[[ $(pwd) =~ /mnt\/c/ ]] && cd ~/temp 
