## @(#):  gnupg-agent setting
#
# @version  1.0.0
# @author   Furukawa Atsushi <atsushifx@gmail.com>
# @since    2025-02-20
# @license  MIT
#
# @desc<<
# This file configures the GPG agent for caching passphrases
# and enables SSH agent support for GPG keys.
#<<

# Cache settings (10 minutes)
default-cache-ttl 600	# 600 seconds = 60 minutes
max-cache-ttl 7200	# 7200 seconds = 120 minutes

# Enable SSH agent support
# GPG agent uses as SSH agent
enable-ssh-support

# pinentry for GUI
pinentry-program = /usr/bin/pinentry-gtk-2
